"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _restaurant_map from './restaurant-map.bones.json'

registerBones({
  "restaurant-map": _restaurant_map,
})
