"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _menu_browser from './menu-browser.bones.json'
import _restaurant_map from './restaurant-map.bones.json'

registerBones({
  "menu-browser": _menu_browser,
  "restaurant-map": _restaurant_map,
})
